---
- name: (CLEANUP) Remove dependencies
  apt:
    name:
      - apt-transport-https
      - curl
      - software-properties-common
    state: absent

- name: (CLEANUP) Check if k3s-uninstall.sh script exists
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: k3s_uninstall_script

- name: (CLEANUP) Remove k3s if the uninstall script exists
  shell: /usr/local/bin/k3s-uninstall.sh
  when: k3s_uninstall_script.stat.exists
  ignore_errors: yes
  register: uninstall_result

- name: (CLEANUP) Display a message if the uninstall script does not exist
  debug:
    msg: "k3s-uninstall.sh script does not exist"
  when: not k3s_uninstall_script.stat.exists

- name: (CLEANUP) Display uninstall result
  debug:
    var: uninstall_result
  when: k3s_uninstall_script.stat.exists

- name: (CLEANUP) Check service status
  command: systemctl list-units --type=service --all | grep -q "k3s.service"
  register: service_exists
  ignore_errors: yes

- name: (CLEANUP) Ensure k3s service is stopped
  systemd:
    name: k3s
    state: stopped
  when: service_exists.rc == 0
  ignore_errors: yes
  register: service_status

- name: (CLEANUP) Check if service is stopped
  assert:
    that:
      - service_exists.rc != 0 or service_status.status.ActiveState == "inactive"
    fail_msg: "The service is still active!"
    success_msg: "The service is inactive or does not exist"
  ignore_errors: yes
