---
- name: (INSTALL) Install dependencies
  apt:
    name:
      - apt-transport-https
      - curl
      - software-properties-common
      - gnupg
    state: present

- name: (INSTALL) Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s_install.sh
    mode: '0700' 

- name: (INSTALL) Run k3s install script
  command: sh /tmp/k3s_install.sh -s - --tls-san {{ cert_path }}/{{ domain_name }} --disable traefik --write-kubeconfig-mode 644
  register: k3s_install_result
  failed_when: k3s_install_result.rc != 0

- name: (INSTALL) Verify service status
  systemd:
    name: k3s
    state: started
  register: service_status

- name: (INSTALL) Verify if service is running
  assert:
    that:
      - service_status.status.ActiveState == "active"
    fail_msg: "The service is not active!"
    success_msg: "The service is active and running correctly."

- name: Set permissions for kubeconfig file
  file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: root
    group: root
    mode: '0600'
  when: ansible_os_family == "Linux"

