---
- name: (INSTALL) Configure DNS local dynamically
  become: True
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['dev'] %}
      {{ hostvars[host]['ansible_host'] }} {{ domain_name }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Create OpenSSL configuration file from template
  template:
    src: openssl.cnf.j2
    dest: /tmp/openssl.cnf

- name: Create a directory for certificates
  file:
    path: "{{ cert_path }}"
    state: directory
    mode: '0700' 

- name: (INSTALL) Generate Private Key
  command: openssl genpkey -algorithm RSA -out {{ cert_path }}/{{ domain_name }}.key  -pkeyopt rsa_keygen_bits:2048

- name: (INSTALL) Generate SSL certificate with SANs
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -key {{ cert_path }}/{{ domain_name }}.key -out {{ cert_path }}/{{ domain_name }}.crt --config /tmp/openssl.cnf


- name: Clean up temporary files
  file:
    path: /tmp/openssl.cnf
    state: absent

- name: Set strict permissions on certificate files
  file:
    path: "{{ cert_path }}/{{ item }}"
    mode: '0600'
  loop:
    - "{{ domain_name }}.key"
    - "{{ domain_name }}.crt"
