---
- name: (INSTALL) Configure DNS local dynamically
  become: True
  blockinfile:
    path: /etc/hosts
    block: |
      {% for host in groups['dev'] %}
      {{ hostvars[host]['ansible_host'] }} {{ host }}
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Create a directory for certificates
  file:
    path: "{{ cert_path }}"
    state: directory
    mode: '0700' 

- name: (INSTALL) Generate TLS certificates - Private Key
  command: openssl genrsa -out {{ cert_path }}/{{ domain_name }}.key 4096  # Stronger key size

- name: (INSTALL) Generate TLS certificates - Certificate Signing Request (CSR)
  command: openssl req -new -key {{ cert_path }}/{{ domain_name }}.key -out {{ cert_path }}/{{ domain_name }}.csr -subj "/CN={{ domain_name }}"

- name: (INSTALL) Generate TLS certificates - Self-Signed Certificate
  command: openssl x509 -req -days 365 -in {{ cert_path }}/{{ domain_name }}.csr -signkey {{ cert_path }}/{{ domain_name }}.key -out {{ cert_path }}/{{ domain_name }}.crt

- name: Set strict permissions on certificate files
  file:
    path: "{{ cert_path }}/{{ item }}"
    mode: '0600'
  loop:
    - "{{ domain_name }}.key"
    - "{{ domain_name }}.csr"
    - "{{ domain_name }}.crt"
